//! Orchestrate table import: walk worksheet rels, resolve table xml
//! paths, parse each, register with the Workbook's `TableTable`.
//!
//! **Why an orchestrator module**: the table → sheet mapping requires
//! coordinating three OOXML parts (worksheet xml, worksheet rels,
//! table xml). Keeping the orchestration here lets `tables_xml.rs`
//! stay a pure parser and `rels.rs` stay generic.

use crate::error::XlsxError;
use crate::read::package::XlsxPackage;
use crate::read::rels::{read_relationships, resolve_rel_target};
use crate::read::tables_xml::{parsed_table_to_metadata, read_table};
use ql_storage::Workbook;
use ql_types::SheetId;

/// Walk every sheet, discover its table parts via `.rels`, parse each
/// table xml, register the metadata with the workbook.
///
/// **W5-D-14c**: this is the table-side closure of Phase 4.11
/// acceptance XLSX-4-03 (names/tables/formats survive round-trip).
/// Tables are now registered with `Workbook::tables_mut().insert()`
/// so they're available for structured-ref binding immediately after
/// import (e.g. `Sales[Qty]` resolves through the engine's
/// `TableTable`).
///
/// # Errors
///
/// - `XlsxError::Zip` / `XlsxError::Io` if the package is malformed
///   or table xml parts are unreadable.
/// - `XlsxError::MalformedOoxml` if a table xml has invalid
///   structure (missing name, invalid ref, etc.).
pub(crate) fn import_tables(
    package: &XlsxPackage,
    workbook: &mut Workbook,
    sheet_names: &[String],
) -> Result<u64, XlsxError> {
    let mut tables_imported: u64 = 0;

    // Iterate over the sheets in workbook order. For each sheet,
    // attempt to read its rels file (which lists the table parts).
    for (sheet_idx, _sheet_name) in sheet_names.iter().enumerate() {
        // Sheet rels live at `xl/worksheets/_rels/sheet{N}.xml.rels`
        // where N is 1-based. Calamine's sheet_names() order matches
        // the workbook.xml order, which matches the sheet{N} numbering
        // for typical xlsx files generated by Excel/LibreOffice/etc.
        // For files with non-standard layouts (gaps in sheet numbers,
        // user-renamed paths) we'd need to follow the workbook rels;
        // W5-D-14c uses the 1:1 ordering which covers the standard
        // case. Tracked as a W5-D-14 follow-up if a fixture exposes it.
        let rels_path = format!("xl/worksheets/_rels/sheet{}.xml.rels", sheet_idx + 1);
        let rels = read_relationships(package, &rels_path)?;

        for rel in rels {
            if !rel.is_table() {
                continue;
            }
            let table_path = resolve_rel_target(&rels_path, &rel.target);
            let parsed = read_table(package, &table_path)?;
            let meta = parsed_table_to_metadata(parsed, sheet_idx as SheetId);
            // Quantbook's TableTable canonicalizes names (uppercase);
            // parsed_table_to_metadata already produces the canonical
            // form, so we pass that through as the key.
            let canonical = meta.name.clone();
            workbook.tables_mut().insert(canonical, meta);
            tables_imported += 1;
        }
    }

    Ok(tables_imported)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn pkg_with_files(files: &[(&str, &str)]) -> XlsxPackage {
        let mut buf = Vec::new();
        {
            let mut zw = zip::ZipWriter::new(std::io::Cursor::new(&mut buf));
            let opts = zip::write::FileOptions::default()
                .compression_method(zip::CompressionMethod::Stored);
            for (name, content) in files {
                zw.start_file(*name, opts).unwrap();
                zw.write_all(content.as_bytes()).unwrap();
            }
            zw.finish().unwrap();
        }
        XlsxPackage::from_bytes(buf)
    }

    #[test]
    fn import_tables_registers_one_table() {
        // Fixture: a workbook with a single sheet containing one
        // table. Verifies the full chain — rels → table xml →
        // TableMetadata → Workbook registration.
        let sheet_rels = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="../tables/table1.xml"/>
</Relationships>"#;
        let table_xml = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<table xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
       id="1" name="Sales" displayName="Sales" ref="A1:C4" headerRowCount="1">
  <tableColumns count="3">
    <tableColumn id="1" name="Date"/>
    <tableColumn id="2" name="Qty" totalsRowFunction="sum"/>
    <tableColumn id="3" name="Price"/>
  </tableColumns>
</table>"#;
        let pkg = pkg_with_files(&[
            ("xl/worksheets/_rels/sheet1.xml.rels", sheet_rels),
            ("xl/tables/table1.xml", table_xml),
        ]);

        let mut wb = Workbook::new();
        wb.add_sheet("Sheet1");
        let n = import_tables(&pkg, &mut wb, &["Sheet1".to_string()]).unwrap();
        assert_eq!(n, 1);
        // Lookup via canonical (uppercase) name.
        let meta = wb.tables().lookup("SALES").expect("table registered");
        assert_eq!(meta.sheet, 0);
        assert_eq!(meta.top_row, 0);
        assert_eq!(meta.top_col, 0);
        assert_eq!(meta.rows, 4);
        assert_eq!(meta.cols, 3);
        assert!(meta.has_header);
        assert!(!meta.has_totals);
        assert_eq!(meta.columns.len(), 3);
    }

    #[test]
    fn import_tables_handles_sheet_with_no_rels() {
        // Sheet without a rels file (no tables, no comments) — the
        // import should succeed and register zero tables.
        let pkg = pkg_with_files(&[("xl/workbook.xml", "<workbook/>")]);
        let mut wb = Workbook::new();
        wb.add_sheet("Sheet1");
        let n = import_tables(&pkg, &mut wb, &["Sheet1".to_string()]).unwrap();
        assert_eq!(n, 0);
    }

    #[test]
    fn import_tables_skips_non_table_relationships() {
        // Sheet with a comments rel but no table rel — should
        // register zero tables.
        let sheet_rels = r#"<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments1.xml"/>
</Relationships>"#;
        let pkg = pkg_with_files(&[("xl/worksheets/_rels/sheet1.xml.rels", sheet_rels)]);
        let mut wb = Workbook::new();
        wb.add_sheet("Sheet1");
        let n = import_tables(&pkg, &mut wb, &["Sheet1".to_string()]).unwrap();
        assert_eq!(n, 0);
    }

    #[test]
    fn import_tables_two_sheets_two_tables() {
        // Each sheet has its own table; verify both are registered
        // with the right sheet_id.
        let rels1 = r#"<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="../tables/table1.xml"/>
</Relationships>"#;
        let rels2 = r#"<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/table" Target="../tables/table2.xml"/>
</Relationships>"#;
        let table1 = r#"<table name="T1" displayName="T1" ref="A1:B2">
  <tableColumns><tableColumn id="1" name="A"/><tableColumn id="2" name="B"/></tableColumns>
</table>"#;
        let table2 = r#"<table name="T2" displayName="T2" ref="A1:C3">
  <tableColumns><tableColumn id="3" name="X"/><tableColumn id="4" name="Y"/><tableColumn id="5" name="Z"/></tableColumns>
</table>"#;
        let pkg = pkg_with_files(&[
            ("xl/worksheets/_rels/sheet1.xml.rels", rels1),
            ("xl/worksheets/_rels/sheet2.xml.rels", rels2),
            ("xl/tables/table1.xml", table1),
            ("xl/tables/table2.xml", table2),
        ]);
        let mut wb = Workbook::new();
        wb.add_sheet("S1");
        wb.add_sheet("S2");
        let n = import_tables(&pkg, &mut wb, &["S1".to_string(), "S2".to_string()]).unwrap();
        assert_eq!(n, 2);
        assert_eq!(wb.tables().lookup("T1").unwrap().sheet, 0);
        assert_eq!(wb.tables().lookup("T2").unwrap().sheet, 1);
        // Stable column ids preserved.
        let t2_cols = &wb.tables().lookup("T2").unwrap().columns;
        assert_eq!(t2_cols[0].id, 3);
        assert_eq!(t2_cols[1].id, 4);
        assert_eq!(t2_cols[2].id, 5);
    }
}
