/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Quantlab. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

// @ts-nocheck
/**
 * QIC Approval Manager
 * Phase 5 - Prompt 05-03
 *
 * Handles change approval/rejection flow with proper security.
 * GAP-05 FIX: Host generates the editScriptHash, webview echoes it back.
 *
 * Flow:
 * 1. Host sends `changes:pending` with `editScriptHash` for each change
 * 2. User clicks Accept/Reject in webview
 * 3. Webview sends `changes:accept` or `changes:reject` with hash
 * 4. Host validates hash, creates ApprovalToken, applies changes
 */

(function() {
	'use strict';

	// ═══════════════════════════════════════════════════════════════════
	// State
	// ═══════════════════════════════════════════════════════════════════

	/** @type {Map<string, string>} changeKey -> editScriptHash */
	const changeHashes = new Map();

	/** @type {Map<string, object>} changeSetId -> changeSet data */
	const changeSets = new Map();

	// ═══════════════════════════════════════════════════════════════════
	// Public API
	// ═══════════════════════════════════════════════════════════════════

	/**
	 * Register a change with its hash (called when host sends changes:pending)
	 * @param {string} changeSetId
	 * @param {string} changeId
	 * @param {string} editScriptHash - Hash generated by host
	 */
	function registerChange(changeSetId, changeId, editScriptHash) {
		const key = `${changeSetId}:${changeId}`;
		changeHashes.set(key, editScriptHash);
	}

	/**
	 * Register a complete change set
	 * @param {object} changeSet
	 */
	function registerChangeSet(changeSet) {
		if (!changeSet || !changeSet.id) return;

		changeSets.set(changeSet.id, changeSet);

		// Register individual change hashes
		if (changeSet.changes && Array.isArray(changeSet.changes)) {
			changeSet.changes.forEach(change => {
				if (change.editScriptHash) {
					registerChange(changeSet.id, change.id, change.editScriptHash);
				}
			});
		}

	}

	/**
	 * Accept a single change
	 * @param {string} changeSetId
	 * @param {string} changeId
	 */
	function acceptChange(changeSetId, changeId) {
		const key = `${changeSetId}:${changeId}`;
		const hash = changeHashes.get(key);

		if (!hash) {
			console.error('[ApprovalManager] No hash for change:', key);
			showError('Unable to approve - missing verification data');
			return;
		}

		// Update UI immediately for responsiveness
		updateChangeStatus(changeId, 'applying', 'Applying...');

		// Send approval with hash (GAP-05: Echo back the hash)
		notifyHost('changes:accept', {
			changeSetId,
			changeId,
			editScriptHash: hash
		});
	}

	/**
	 * Reject a single change
	 * @param {string} changeSetId
	 * @param {string} changeId
	 */
	function rejectChange(changeSetId, changeId) {
		// Update UI
		updateChangeStatus(changeId, 'rejected', 'Rejected');

		// Send rejection (no hash needed for rejection)
		notifyHost('changes:reject', {
			changeSetId,
			changeId
		});

		// Cleanup hash
		const key = `${changeSetId}:${changeId}`;
		changeHashes.delete(key);
	}

	/**
	 * Accept all changes in a change set
	 * @param {string} changeSetId
	 */
	function acceptAll(changeSetId) {
		const changeSet = changeSets.get(changeSetId);
		if (!changeSet) {
			console.error('[ApprovalManager] Change set not found:', changeSetId);
			return;
		}

		// Collect hashes for all pending changes
		const changes = changeSet.changes || [];
		const acceptPayload = {
			changeSetId,
			changes: []
		};

		changes.forEach(change => {
			if (change.status === 'pending') {
				const key = `${changeSetId}:${change.id}`;
				const hash = changeHashes.get(key);
				if (hash) {
					acceptPayload.changes.push({
						changeId: change.id,
						editScriptHash: hash
					});
					updateChangeStatus(change.id, 'applying', 'Applying...');
				}
			}
		});

		if (acceptPayload.changes.length > 0) {
			notifyHost('changes:acceptAll', acceptPayload);
		}
	}

	/**
	 * Reject all changes in a change set
	 * @param {string} changeSetId
	 */
	function rejectAll(changeSetId) {
		const changeSet = changeSets.get(changeSetId);
		if (!changeSet) return;

		const changes = changeSet.changes || [];
		const changeIds = [];

		changes.forEach(change => {
			if (change.status === 'pending') {
				updateChangeStatus(change.id, 'rejected', 'Rejected');
				changeIds.push(change.id);

				// Cleanup hash
				const key = `${changeSetId}:${change.id}`;
				changeHashes.delete(key);
			}
		});

		if (changeIds.length > 0) {
			notifyHost('changes:rejectAll', {
				changeSetId,
				changeIds
			});
		}
	}

	/**
	 * Retry failed changes
	 * @param {string} changeSetId
	 */
	function retryFailed(changeSetId) {
		const changeSet = changeSets.get(changeSetId);
		if (!changeSet) return;

		const changes = changeSet.changes || [];
		const retryChanges = [];

		changes.forEach(change => {
			if (change.status === 'failed' || change.status === 'conflict') {
				const key = `${changeSetId}:${change.id}`;
				const hash = changeHashes.get(key);
				if (hash) {
					retryChanges.push({
						changeId: change.id,
						editScriptHash: hash
					});
					updateChangeStatus(change.id, 'applying', 'Retrying...');
				}
			}
		});

		if (retryChanges.length > 0) {
			notifyHost('changes:retry', {
				changeSetId,
				changes: retryChanges
			});
		}
	}

	// ═══════════════════════════════════════════════════════════════════
	// UI Updates
	// ═══════════════════════════════════════════════════════════════════

	/**
	 * Update change card status in UI
	 * @param {string} changeId
	 * @param {string} status
	 * @param {string} [message]
	 */
	function updateChangeStatus(changeId, status, message) {
		// Update via QicChangeCards if available
		if (window.QicChangeCards?.updateCardStatus) {
			window.QicChangeCards.updateCardStatus(changeId, status, message);
			return;
		}

		// Fallback: direct DOM update
		const card = document.querySelector(`[data-change-id="${changeId}"]`);
		if (!card) return;

		card.dataset.status = status;

		const statusText = card.querySelector('.status-text');
		if (statusText) {
			statusText.textContent = message || getStatusText(status);
		}

		// Update the stored change set data
		for (const [, changeSet] of changeSets) {
			const change = changeSet.changes?.find(c => c.id === changeId);
			if (change) {
				change.status = status;
				break;
			}
		}
	}

	/**
	 * Get default status text
	 * @param {string} status
	 * @returns {string}
	 */
	function getStatusText(status) {
		const texts = {
			pending: 'Pending',
			applying: 'Applying...',
			applied: 'Applied successfully',
			rejected: 'Rejected',
			failed: 'Failed',
			conflict: 'Conflict detected'
		};
		return texts[status] || status;
	}

	/**
	 * Show change-specific error
	 * @param {string} changeId
	 * @param {string} error
	 */
	function showChangeError(changeId, error) {
		updateChangeStatus(changeId, 'failed', error);
	}

	/**
	 * Show general error via toast
	 * @param {string} message
	 */
	function showError(message) {
		if (window.qicToast?.show) {
			window.qicToast.show(message, 'error');
		} else {
			console.error('[ApprovalManager]', message);
		}
	}

	// ═══════════════════════════════════════════════════════════════════
	// Message Handling
	// ═══════════════════════════════════════════════════════════════════

	/**
	 * Handle incoming messages related to changes
	 * @param {object} msg
	 * @returns {boolean} true if handled
	 */
	function handleMessage(msg) {
		switch (msg.type) {
			case 'changes:pending':
			case 'diff-preview':
				// Register the change set and its hashes
				if (msg.payload) {
					registerChangeSet(msg.payload);
				}
				return true;

			case 'changes:fileStatus':
			case 'change:statusUpdate':
				// Handle status update from host
				handleStatusUpdate(msg.payload || msg);
				return true;

			case 'changes:resolved':
				// All changes in set resolved - cleanup
				handleChangesResolved(msg.payload);
				return true;

			case 'changes:error':
				// General error
				if (msg.payload?.changeId) {
					showChangeError(msg.payload.changeId, msg.payload.error);
				} else {
					showError(msg.payload?.error || 'An error occurred');
				}
				return true;

			default:
				return false;
		}
	}

	/**
	 * Handle status update from host
	 * @param {object} payload
	 */
	function handleStatusUpdate(payload) {
		if (!payload) return;

		const { changeSetId, changeId, status, message, error } = payload;

		updateChangeStatus(changeId, status, message || error);

		// Cleanup hash on completion
		if (status === 'applied' || status === 'rejected') {
			const key = `${changeSetId}:${changeId}`;
			changeHashes.delete(key);
		}
	}

	/**
	 * Handle changes resolved (all done)
	 * @param {object} payload
	 */
	function handleChangesResolved(payload) {
		if (!payload?.id) return;

		const changeSetId = payload.id;

		// Clear all hashes for this change set
		const prefix = `${changeSetId}:`;
		for (const key of changeHashes.keys()) {
			if (key.startsWith(prefix)) {
				changeHashes.delete(key);
			}
		}

		// Remove from tracked change sets
		changeSets.delete(changeSetId);
	}

	// ═══════════════════════════════════════════════════════════════════
	// Helpers
	// ═══════════════════════════════════════════════════════════════════

	/**
	 * Send message to host
	 * @param {string} type
	 * @param {object} payload
	 */
	function notifyHost(type, payload) {
		const vscode = window.vscode || (window.acquireVsCodeApi && window.acquireVsCodeApi());
		if (vscode) {
			vscode.postMessage({ type, payload });
		}
	}

	/**
	 * Get change set by ID
	 * @param {string} changeSetId
	 * @returns {object|undefined}
	 */
	function getChangeSet(changeSetId) {
		return changeSets.get(changeSetId);
	}

	/**
	 * Get hash for a change
	 * @param {string} changeSetId
	 * @param {string} changeId
	 * @returns {string|undefined}
	 */
	function getChangeHash(changeSetId, changeId) {
		const key = `${changeSetId}:${changeId}`;
		return changeHashes.get(key);
	}

	// ═══════════════════════════════════════════════════════════════════
	// Export
	// ═══════════════════════════════════════════════════════════════════

	window.QicApproval = {
		// Registration
		registerChange,
		registerChangeSet,

		// Actions
		acceptChange,
		rejectChange,
		acceptAll,
		rejectAll,
		retryFailed,

		// Message handling
		handleMessage,

		// Getters
		getChangeSet,
		getChangeHash,

		// Debug
		_debug: {
			getHashes: () => new Map(changeHashes),
			getChangeSets: () => new Map(changeSets)
		}
	};

})();
