/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * Visualise v2 -- Promote to Chart.
 *
 * Generates a minimal `.py` scaffold from a timeseries `.qviz.json` so the
 * user can re-open the same dataset in Quantlab's Chart view. The Chart
 * view (registered against `*.py` per package.json's
 * `quantlab.chartView` contribution) brings live data, indicators,
 * trading sessions, and Trade-fill overlays -- surface Visualise itself
 * does not reproduce.
 *
 * The scaffold is INTENTIONALLY minimal: it plots a single series via
 * `chart.plot(data.<field>)` and leaves indicator wiring to the user in
 * Chart's own UI. Transform-to-indicator translation (e.g., Visualise's
 * `window fn=rolling_mean` -> Chart's SMA indicator) is deferred to v2.1.
 *
 * Pure module: path math + scaffold string composition + idempotency
 * check live here; the provider does the actual fs writes (so this
 * module stays vscode-free and unit-testable).
 */

import * as path from 'path';
import * as fs from 'fs';

import type { QvizSpec } from './spec';
import { resolveDatasetPath } from './persist';

/** Marker that identifies a scaffold as auto-generated. Idempotent
 *  overwrite is gated on the presence of this exact line in the first
 *  few lines of the existing file. Hand-edited scaffolds (header
 *  removed) are refused to protect user work. */
export const PROMOTE_SCAFFOLD_HEADER_MARKER
	= '# Auto-generated by Quantlab Visualise -> Promote to Chart.';

/** Subdirectory under the workspace root where scaffolds land. */
export const SCAFFOLD_SUBDIR = path.join('.quantlab', 'visualise-promoted');

/** Result variants. Discriminate on `kind`. */
export type PromoteScaffoldResult =
	| { kind: 'ok'; scaffoldPath: string; scaffoldBody: string }
	| { kind: 'error'; message: string };

export interface GenerateOptions {
	/** When supplied, the file at `scaffoldPath` is read to decide
	 *  whether overwriting is safe. Pure callers (tests) can omit this
	 *  to skip the disk-touch idempotency check; the provider passes
	 *  `fs.readFileSync` so the check runs. */
	readonly readExistingFile?: (absPath: string) => string | null;
	/** Override of the timestamp embedded in the scaffold header.
	 *  Tests pass a fixed value so snapshot assertions are stable. */
	readonly nowIso?: string;
}

/**
 * Compose the scaffold path + body for a Visualise spec.
 *
 * Refuses (returns `{ kind: 'error' }`) when:
 *   - chart family is not 'timeseries' (Chart view is OHLCV-only).
 *   - the spec's `dataset.uri` doesn't resolve to a real file under the
 *     workspace.
 *   - a non-auto-generated file already exists at the scaffold path
 *     (user hand-edited the destination; overwriting would lose work).
 *
 * Returns the path + body on success; caller writes to disk.
 */
export function generatePromoteScaffold(
	spec: QvizSpec,
	specUri: string,
	workspaceRoot: string,
	opts: GenerateOptions = {},
): PromoteScaffoldResult {
	// Step 1: refuse non-timeseries.
	if (spec.chart.family !== 'timeseries') {
		return {
			kind: 'error',
			message: `Promote to Chart only supports timeseries specs. The current spec is ${spec.chart.family}/${spec.chart.type}. Switch to a timeseries chart type (line/area/bar/histogram/candlestick/baseline) and try again.`,
		};
	}

	// Step 2: resolve the dataset URI to an absolute path. Reuses the
	// same resolver the editor uses to load the spec -- if it can't
	// resolve, the Chart view wouldn't be able to either.
	const resolved = resolveDatasetPath(spec.dataset.uri, workspaceRoot);
	if (resolved.kind !== 'ok') {
		return {
			kind: 'error',
			message: `Cannot promote: dataset unresolvable (${resolved.kind}). Fix the dataset path in the spec first.`,
		};
	}

	// Step 3: pick the field to plot.
	const yField = pickYField(spec);
	if (yField === null) {
		return {
			kind: 'error',
			message: `Cannot promote: no plottable encoding found. Set y (or ohlcv.close for candlestick) in the spec first.`,
		};
	}

	// Step 4: derive the scaffold path. Use the relative path from
	// workspaceRoot to the spec's filename to disambiguate when multiple
	// specs share a leaf name. Replace path separators with `__` so the
	// scaffold lives flat in `.quantlab/visualise-promoted/`.
	const specAbs = path.resolve(specUri);
	const relSpec = path.relative(workspaceRoot, specAbs);
	// Megaudit Theme G (G15, 2026-05-13): widen the regex to catch
	// Unicode line/paragraph separators (U+2028, U+2029) and the C0/C1
	// control range. Without this, an exotic basename could produce a
	// scaffold filename that downstream tools interpret as containing a
	// newline. The path containment check at write time blocks the
	// directory-escape vector; this closes the cosmetic/filename-shape
	// gap.
	const sanitized = relSpec
		.replace(/\.qviz\.json$/i, '')
		.replace(/[/\\\x00-\x1f\u2028\u2029]/g, '__');
	const scaffoldRel = path.join(SCAFFOLD_SUBDIR, sanitized + '.py');
	const scaffoldPath = path.resolve(workspaceRoot, scaffoldRel);

	// Step 5: idempotency check. If a file already exists at the
	// destination AND lacks the header marker, refuse -- a hand-edited
	// scaffold should not be silently overwritten.
	if (opts.readExistingFile) {
		const existing = opts.readExistingFile(scaffoldPath);
		if (existing !== null && !existing.includes(PROMOTE_SCAFFOLD_HEADER_MARKER)) {
			return {
				kind: 'error',
				message: `${scaffoldRel} exists and has been hand-edited (auto-generated header is missing). Remove or rename the file to re-promote.`,
			};
		}
	}

	// Step 6: compose the scaffold body.
	const specRelForComment = relSpec.replace(/\\/g, '/');
	const nowIso = opts.nowIso ?? new Date().toISOString();
	const scaffoldBody = composeScaffoldBody({
		specRelPath: specRelForComment,
		datasetAbsPath: resolved.absPath,
		datasetUri: spec.dataset.uri,
		chartType: spec.chart.type,
		yField,
		nowIso,
	});

	return { kind: 'ok', scaffoldPath, scaffoldBody };
}

/** Convenience wrapper: read existing-file via fs.readFileSync. The
 *  provider calls this; tests pass their own reader stub. */
export function readExistingScaffold(absPath: string): string | null {
	try {
		return fs.readFileSync(absPath, 'utf8');
	} catch (e) {
		if ((e as NodeJS.ErrnoException).code === 'ENOENT') { return null; }
		throw e;
	}
}

// ---------------------------------------------------------------------------
// internals
// ---------------------------------------------------------------------------

/** Pick the field to plot in the scaffold:
 *   - candlestick: always `close` (the natural single-line projection).
 *   - line/area/bar/histogram/baseline: the `y` encoding's field. Falls
 *     back to `close` only when there's NO y encoding AND the dataset
 *     likely has OHLCV columns. Returns null when no candidate exists.
 */
function pickYField(spec: QvizSpec): string | null {
	if (spec.chart.type === 'candlestick') {
		// Candlestick spec is required to have ohlcv.close per the
		// validator; defensive fallback for partial specs.
		return spec.chart.encodings.ohlcv?.close ?? 'close';
	}
	const y = spec.chart.encodings.y;
	if (y && typeof y.field === 'string' && y.field.length > 0) {
		return y.field;
	}
	return null;
}

interface ScaffoldFields {
	readonly specRelPath: string;
	readonly datasetAbsPath: string;
	readonly datasetUri: string;
	readonly chartType: string;
	readonly yField: string;
	readonly nowIso: string;
}

/** Compose the scaffold .py body. The VisualizationRunner parser only
 *  accepts `data.<open|high|low|close|volume>` for series sources, so
 *  fields outside that set get plotted as `data.close` with a TODO
 *  comment naming the original encoding. The user fixes the wiring in
 *  Chart's UI. */
function composeScaffoldBody(fields: ScaffoldFields): string {
	const knownOhlcv = new Set(['open', 'high', 'low', 'close', 'volume']);
	const useField = knownOhlcv.has(fields.yField.toLowerCase())
		? fields.yField.toLowerCase()
		: 'close';
	const todoLine = useField === fields.yField.toLowerCase()
		? ''
		: `# TODO: the original spec's y-encoding was '${fields.yField}' which is\n`
			+ `#       not an OHLCV column the Chart view's plot parser accepts.\n`
			+ `#       Defaulting to close. Swap the line below to your column once\n`
			+ `#       you've loaded the dataset into the Chart view.\n`;
	return [
		PROMOTE_SCAFFOLD_HEADER_MARKER,
		`# Source spec: ${fields.specRelPath}`,
		`# Generated at: ${fields.nowIso}`,
		`#`,
		`# This .py opens in the Chart view bound to the same dataset.`,
		`# Re-running "Promote to Chart" overwrites this file IF the header`,
		`# above is still present. Remove the header to protect manual edits.`,
		`#`,
		`# Original chart type: ${fields.chartType}`,
		`# Dataset URI:         ${fields.datasetUri}`,
		`# Dataset abs path:    ${fields.datasetAbsPath}`,
		``,
		todoLine,
		`def visualize(chart, data, params):`,
		`    """Auto-generated minimal plot. Add indicators below via Chart's UI`,
		`    or by hand using the chart.* API."""`,
		`    chart.plot(data.${useField})`,
		``,
	].join('\n');
}
