"""
HTML Report Generator.

Generates visual HTML reports for sharing and archival.

Spec Reference: Technical Spec §17.4, Decision K64
"""

from datetime import datetime
from datetime import timezone
from decimal import Decimal
from pathlib import Path
from typing import Any


class HTMLReportGenerator:
    """
    HTML report generator for backtest results.

    Produces a standalone HTML file with:
    - Summary metrics
    - Equity curve chart (SVG)
    - Trade list
    - Monthly returns heatmap
    """

    def __init__(
        self,
        strategy_name: str | None = None,
        strategy_file: str | None = None,
    ) -> None:
        self.strategy_name = strategy_name or "Strategy"
        self.strategy_file = strategy_file or ""

    def generate(
        self,
        output_path: Path,
        metrics: dict[str, Any],
        trades: list[dict[str, Any]],
        equity_curve: list[dict[str, Any]] | None = None,
        parameters: dict[str, Any] | None = None,
    ) -> Path:
        """
        Generate HTML report.

        Args:
            output_path: Path to write HTML file
            metrics: Performance metrics
            trades: Trade records
            equity_curve: Optional equity curve data
            parameters: Optional strategy parameters

        Returns:
            Path to written file
        """
        html = self._render_report(metrics, trades, equity_curve, parameters)

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)

        return output_path

    def generate_string(
        self,
        metrics: dict[str, Any],
        trades: list[dict[str, Any]],
        equity_curve: list[dict[str, Any]] | None = None,
        parameters: dict[str, Any] | None = None,
    ) -> str:
        """Generate HTML report as string."""
        return self._render_report(metrics, trades, equity_curve, parameters)

    def _render_report(
        self,
        metrics: dict[str, Any],
        trades: list[dict[str, Any]],
        equity_curve: list[dict[str, Any]] | None,
        parameters: dict[str, Any] | None,
    ) -> str:
        """Render the complete HTML report."""
        metrics_section = self._render_metrics(metrics)
        trades_section = self._render_trades(trades)
        equity_section = self._render_equity_curve(equity_curve) if equity_curve else ""
        params_section = self._render_parameters(parameters) if parameters else ""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quantlab Report - {self._escape(self.strategy_name)}</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Quantlab Backtest Report</h1>
            <div class="subtitle">{self._escape(self.strategy_name)}</div>
            <div class="timestamp">Generated: {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}</div>
        </header>

        <section class="summary">
            <h2>Performance Summary</h2>
            {metrics_section}
        </section>

        {equity_section}

        {params_section}

        <section class="trades">
            <h2>Trade History ({len(trades)} trades)</h2>
            {trades_section}
        </section>

        <footer>
            <p>Generated by Quantlab v10.0</p>
        </footer>
    </div>
</body>
</html>"""

    def _render_metrics(self, metrics: dict[str, Any]) -> str:
        """Render metrics grid."""
        cards = []

        # Key metrics to highlight
        key_metrics = [
            ("total_return", "Total Return", self._format_percent),
            ("cagr", "CAGR", self._format_percent),
            ("sharpe_ratio", "Sharpe Ratio", self._format_number),
            ("max_drawdown", "Max Drawdown", self._format_percent),
            ("win_rate", "Win Rate", self._format_percent),
            ("profit_factor", "Profit Factor", self._format_number),
            ("total_trades", "Total Trades", lambda x: str(int(x)) if x else "0"),
            ("avg_holding_period", "Avg Holding", lambda x: f"{x:.1f} bars" if x else "N/A"),
        ]

        for key, label, formatter in key_metrics:
            value = metrics.get(key, "N/A")
            formatted = formatter(value) if value not in (None, "N/A") else "N/A"
            css_class = self._get_value_class(key, value)
            cards.append(f"""
                <div class="metric-card">
                    <div class="metric-label">{label}</div>
                    <div class="metric-value {css_class}">{formatted}</div>
                </div>
            """)

        # Additional metrics table
        additional_rows = []
        for key, value in metrics.items():
            if key not in [m[0] for m in key_metrics]:
                formatted = self._format_value(value)
                additional_rows.append(f"""
                    <tr>
                        <td>{self._format_key(key)}</td>
                        <td>{formatted}</td>
                    </tr>
                """)

        additional_table = ""
        if additional_rows:
            additional_table = f"""
                <div class="additional-metrics">
                    <h3>Additional Metrics</h3>
                    <table>
                        <tbody>
                            {"".join(additional_rows)}
                        </tbody>
                    </table>
                </div>
            """

        return f"""
            <div class="metrics-grid">
                {"".join(cards)}
            </div>
            {additional_table}
        """

    def _render_trades(self, trades: list[dict[str, Any]]) -> str:
        """Render trades table."""
        if not trades:
            return "<p>No trades executed.</p>"

        rows = []
        for trade in trades[:100]:  # Limit to first 100
            pnl = trade.get("pnl", 0)
            pnl_class = "positive" if float(pnl) > 0 else "negative" if float(pnl) < 0 else ""

            rows.append(f"""
                <tr>
                    <td>{trade.get('symbol', 'N/A')}</td>
                    <td>{trade.get('side', 'N/A')}</td>
                    <td>{self._format_value(trade.get('quantity'))}</td>
                    <td>{self._format_price(trade.get('entry_price'))}</td>
                    <td>{self._format_price(trade.get('exit_price'))}</td>
                    <td>{self._format_time(trade.get('entry_time'))}</td>
                    <td>{self._format_time(trade.get('exit_time'))}</td>
                    <td class="{pnl_class}">{self._format_currency(pnl)}</td>
                </tr>
            """)

        more_note = ""
        if len(trades) > 100:
            more_note = f"<p><em>Showing first 100 of {len(trades)} trades</em></p>"

        return f"""
            <div class="table-wrapper">
                <table class="trades-table">
                    <thead>
                        <tr>
                            <th>Symbol</th>
                            <th>Side</th>
                            <th>Qty</th>
                            <th>Entry</th>
                            <th>Exit</th>
                            <th>Entry Time</th>
                            <th>Exit Time</th>
                            <th>P&L</th>
                        </tr>
                    </thead>
                    <tbody>
                        {"".join(rows)}
                    </tbody>
                </table>
            </div>
            {more_note}
        """

    def _render_equity_curve(self, equity_curve: list[dict[str, Any]]) -> str:
        """Render equity curve as SVG chart."""
        if not equity_curve or len(equity_curve) < 2:
            return ""

        # Extract data
        equities = [float(p.get("equity", 0)) for p in equity_curve]
        min_eq = min(equities)
        max_eq = max(equities)
        range_eq = max_eq - min_eq or 1

        # SVG dimensions
        width = 800
        height = 300
        padding = 40

        # Generate path
        points = []
        for i, eq in enumerate(equities):
            x = padding + (i / (len(equities) - 1)) * (width - 2 * padding)
            y = height - padding - ((eq - min_eq) / range_eq) * (height - 2 * padding)
            points.append(f"{x:.1f},{y:.1f}")

        path_d = f"M {' L '.join(points)}"

        # Y-axis labels
        y_labels = []
        for i in range(5):
            value = min_eq + (i / 4) * range_eq
            y = height - padding - (i / 4) * (height - 2 * padding)
            y_labels.append(f'<text x="{padding - 5}" y="{y}" class="y-label">${value:,.0f}</text>')

        return f"""
            <section class="equity-curve">
                <h2>Equity Curve</h2>
                <svg viewBox="0 0 {width} {height}" class="chart">
                    <!-- Grid lines -->
                    <line x1="{padding}" y1="{padding}" x2="{padding}" y2="{height - padding}" class="axis" />
                    <line x1="{padding}" y1="{height - padding}" x2="{width - padding}" y2="{height - padding}" class="axis" />

                    <!-- Y-axis labels -->
                    {"".join(y_labels)}

                    <!-- Equity curve -->
                    <path d="{path_d}" class="equity-line" />
                </svg>
            </section>
        """

    def _render_parameters(self, parameters: dict[str, Any]) -> str:
        """Render strategy parameters."""
        if not parameters:
            return ""

        rows = []
        for key, value in parameters.items():
            rows.append(f"""
                <tr>
                    <td>{self._format_key(key)}</td>
                    <td>{self._format_value(value)}</td>
                </tr>
            """)

        return f"""
            <section class="parameters">
                <h2>Strategy Parameters</h2>
                <table>
                    <tbody>
                        {"".join(rows)}
                    </tbody>
                </table>
            </section>
        """

    def _get_styles(self) -> str:
        """Get CSS styles."""
        return """
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                line-height: 1.5;
                color: #333;
                background: #f5f5f5;
            }
            .container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
            }
            header {
                background: linear-gradient(135deg, #1a1a2e, #16213e);
                color: white;
                padding: 30px;
                border-radius: 8px;
                margin-bottom: 20px;
            }
            header h1 { font-size: 24px; margin-bottom: 8px; }
            .subtitle { font-size: 18px; opacity: 0.9; }
            .timestamp { font-size: 12px; opacity: 0.7; margin-top: 10px; }
            section {
                background: white;
                border-radius: 8px;
                padding: 20px;
                margin-bottom: 20px;
                box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            }
            h2 {
                font-size: 18px;
                margin-bottom: 16px;
                color: #333;
                border-bottom: 2px solid #eee;
                padding-bottom: 8px;
            }
            h3 { font-size: 14px; margin: 16px 0 8px; color: #666; }
            .metrics-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
                gap: 16px;
            }
            .metric-card {
                background: #f8f9fa;
                padding: 16px;
                border-radius: 6px;
                text-align: center;
            }
            .metric-label {
                font-size: 12px;
                color: #666;
                text-transform: uppercase;
                margin-bottom: 4px;
            }
            .metric-value {
                font-size: 24px;
                font-weight: 600;
            }
            .positive { color: #22c55e; }
            .negative { color: #ef4444; }
            .neutral { color: #666; }
            table {
                width: 100%;
                border-collapse: collapse;
                font-size: 14px;
            }
            th, td {
                padding: 10px 12px;
                text-align: left;
                border-bottom: 1px solid #eee;
            }
            th {
                background: #f8f9fa;
                font-weight: 600;
                color: #666;
            }
            .table-wrapper { overflow-x: auto; }
            .trades-table td { font-family: monospace; }
            .equity-curve svg {
                width: 100%;
                height: 300px;
            }
            .axis { stroke: #ddd; stroke-width: 1; }
            .equity-line {
                fill: none;
                stroke: #3b82f6;
                stroke-width: 2;
            }
            .y-label {
                font-size: 10px;
                text-anchor: end;
                fill: #666;
            }
            footer {
                text-align: center;
                color: #999;
                font-size: 12px;
                padding: 20px;
            }
            @media print {
                body { background: white; }
                .container { max-width: none; }
                section { box-shadow: none; border: 1px solid #ddd; }
            }
        """

    def _escape(self, text: str) -> str:
        """HTML escape text."""
        return (
            text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
        )

    def _format_percent(self, value: Any) -> str:
        """Format as percentage."""
        if value is None:
            return "N/A"
        try:
            v = float(value)
            return f"{v * 100:.2f}%"
        except (ValueError, TypeError):
            return str(value)

    def _format_number(self, value: Any) -> str:
        """Format as number."""
        if value is None:
            return "N/A"
        try:
            v = float(value)
            return f"{v:.2f}"
        except (ValueError, TypeError):
            return str(value)

    def _format_currency(self, value: Any) -> str:
        """Format as currency."""
        if value is None:
            return "N/A"
        try:
            v = float(value)
            return f"${v:,.2f}"
        except (ValueError, TypeError):
            return str(value)

    def _format_price(self, value: Any) -> str:
        """Format as price."""
        if value is None:
            return "N/A"
        try:
            v = float(value)
            return f"${v:.2f}"
        except (ValueError, TypeError):
            return str(value)

    def _format_time(self, value: Any) -> str:
        """Format timestamp."""
        if value is None:
            return "N/A"
        if isinstance(value, datetime):
            return value.strftime("%Y-%m-%d %H:%M")
        return str(value)[:16] if len(str(value)) > 16 else str(value)

    def _format_value(self, value: Any) -> str:
        """Format any value."""
        if value is None:
            return "N/A"
        if isinstance(value, Decimal):
            return str(value)
        if isinstance(value, float):
            if value != value:  # NaN check
                return "N/A"
            return f"{value:.4f}"
        if isinstance(value, datetime):
            return value.isoformat()
        return str(value)

    def _format_key(self, key: str) -> str:
        """Format metric key for display."""
        return key.replace("_", " ").title()

    def _get_value_class(self, key: str, value: Any) -> str:
        """Get CSS class based on value."""
        if value is None or value == "N/A":
            return "neutral"

        try:
            v = float(value)
            if key in ("total_return", "cagr", "pnl"):
                return "positive" if v > 0 else "negative" if v < 0 else "neutral"
            if key == "max_drawdown":
                return "negative" if v < -0.1 else "neutral"
            if key == "sharpe_ratio":
                return "positive" if v > 1 else "negative" if v < 0 else "neutral"
            if key == "win_rate":
                return "positive" if v > 0.5 else "negative" if v < 0.4 else "neutral"
        except (ValueError, TypeError):
            pass

        return "neutral"


def export_to_html(
    output_path: Path | str,
    metrics: dict[str, Any],
    trades: list[dict[str, Any]],
    strategy_name: str | None = None,
    equity_curve: list[dict[str, Any]] | None = None,
    parameters: dict[str, Any] | None = None,
) -> Path:
    """
    Convenience function to export results to HTML.

    Args:
        output_path: Path for output file
        metrics: Performance metrics
        trades: Trade records
        strategy_name: Optional strategy name
        equity_curve: Optional equity curve data
        parameters: Optional strategy parameters

    Returns:
        Path to written file
    """
    generator = HTMLReportGenerator(strategy_name=strategy_name)
    output_path = Path(output_path)
    return generator.generate(output_path, metrics, trades, equity_curve, parameters)
