[package]
name = "ql-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
arrow-array  = { workspace = true }
arrow-schema = { workspace = true }
criterion    = { workspace = true }
num_cpus     = { workspace = true }
