[package]
name = "ql-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ql-types     = { path = "../ql-types" }
arrow-array  = { workspace = true }
arrow-schema = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
