[package]
name = "ql-exec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ql-types          = { path = "../ql-types" }
ql-formula-syntax = { path = "../ql-formula-syntax" }
ql-calcgraph     = { path = "../ql-calcgraph" }
ql-storage        = { path = "../ql-storage" }

[dev-dependencies]
proptest = { workspace = true }
